package utils

import (
	"math/rand"
	"net/smtp"
	"os"
	"time"
)

func AutoGeneratedPassword() string {
	const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	var seededRand *rand.Rand = rand.New(rand.NewSource(time.Now().UnixNano()))
	b := make([]byte, 8)
	for i := range b {
		b[i] = charset[seededRand.Intn(len(charset))]
	}
	return string(b)
}

func CreateAdminTemplate(email, password string) string {
	return "Email: " + email + "\nPassword: " + password
}

func SendEmail(to, body, subject string) error {
	from := os.Getenv("EMAIL")
	password := os.Getenv("EMAIL_PASSWORD")
	host := os.Getenv("SMTP_HOST")
	port := os.Getenv("SMTP_PORT")

	auth := smtp.PlainAuth("", from, password, host)
	msg := []byte("To: " + to + "\n" +
		"Subject: " + subject + "\n" +
		"\n" +
		body + "\n")

	addr := host + ":" + port
	return smtp.SendMail(addr, auth, from, []string{to}, msg)
}
